import type { MetadataRoute } from "next";

/**
 * Web App Manifest — lets the site be installed on a phone home-screen
 * and gives Chrome / Edge / Brave the metadata they need for PWA-ish
 * features (theme color, splash background, app name).
 *
 * Icons reference the dynamic /icon and /apple-icon routes generated by
 * src/app/icon.tsx and src/app/apple-icon.tsx.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "VocazAI — Trilingual AI Voice Agent",
    short_name: "VocazAI",
    description:
      "Trilingual AI voice receptionist (French · Arabic · English) — 24/7 phone reception, appointment booking, lead qualification.",
    start_url: "/fr",
    scope: "/",
    display: "standalone",
    background_color: "#0E0D0B",
    theme_color: "#2F6B49",
    orientation: "portrait-primary",
    lang: "fr",
    categories: ["business", "productivity", "communication"],
    icons: [
      { src: "/icon", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/apple-icon", sizes: "180x180", type: "image/png", purpose: "any" },
    ],
  };
}
